## Numpy Array Indexing

In [1]:
import numpy as np

In [2]:
a = np.arange(0,11)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[0]

0

In [5]:
a[3]

3

In [6]:
a[1:5]

array([1, 2, 3, 4])

In [7]:
a[:4]

array([0, 1, 2, 3])

In [8]:
a[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_of_a = a[0:6]

In [11]:
slice_of_a

array([0, 1, 2, 3, 4, 5])

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_a = 10

In [14]:
slice_of_a

10

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_a = a[0:5]

In [18]:
slice_of_a

array([0, 1, 2, 3, 4])

In [19]:
slice_of_a[:] = 9

In [20]:
slice_of_a

array([9, 9, 9, 9, 9])

In [21]:
a

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

## It is called broadcasting of Array , due to memory numpy not only change the value of the slice of array but it also changed the original array

## If we need our original array should not be affected the we need to use copy method

In [22]:
a

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [23]:
b = a.copy()

In [24]:
b

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [25]:
slice_of_b = b[0:5]

In [26]:
slice_of_b

array([9, 9, 9, 9, 9])

In [27]:
slice_of_b[:] = 24

In [28]:
slice_of_b

array([24, 24, 24, 24, 24])

In [29]:
b

array([24, 24, 24, 24, 24,  5,  6,  7,  8,  9, 10])

In [30]:
a

array([ 9,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

## Here we can see the original array (a) is unchanged whereas the array (b) has changed

## Creating a 2-D array

In [31]:
a_2d = np.array([[5,10,15],[20,25,30],[35,40,45],[50,55,60]])

In [32]:
a_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

## Get the item from a 2-D Array

In [33]:
a_2d[1,1]

25

In [34]:
a_2d[3,2]

60

In [35]:
a_2d[0,2] = 100

In [36]:
a_2d

array([[  5,  10, 100],
       [ 20,  25,  30],
       [ 35,  40,  45],
       [ 50,  55,  60]])

## If we want to return the ROW

In [37]:
a_2d[0]

array([  5,  10, 100])

In [40]:
a_2d[:2]

array([[  5,  10, 100],
       [ 20,  25,  30]])

In [41]:
a_2d[:2,1:]

array([[ 10, 100],
       [ 25,  30]])

## Boolean in array

In [43]:
b = np.arange(10,20)

In [44]:
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
b > 15

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [46]:
b >= 15

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
b < 20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## Array Collection

In [48]:
c = np.arange(0,11)

In [49]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
bool_c = c > 5

In [51]:
bool_c

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [52]:
c[bool_c]

array([ 6,  7,  8,  9, 10])

## Here the array will return all the True Value

In [53]:
c[c>4]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
c[c<6]

array([0, 1, 2, 3, 4, 5])

## Creating a 2-D array from 1-D array

In [55]:
d = np.arange(0,50)

In [56]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [57]:
e = np.arange(0,50).reshape(5,10)

In [58]:
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

## Lets say we need to get the value from 23,24 and 33,34

In [59]:
e[2:4,3:5]

array([[23, 24],
       [33, 34]])