## Numpy Operations

### array with array

In [1]:
import numpy as np

In [2]:
a = np.arange(10,21)

In [3]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
b = a + a

In [5]:
b

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [6]:
d = a - a

In [7]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
e = a * d

In [10]:
e

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
f = a * a

In [12]:
f

array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400])

In [13]:
g = f / a

In [14]:
g

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

## Array with scaler

In [15]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
h = a - 5

In [17]:
h

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
a ** 3

array([1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000],
      dtype=int32)

## In mathematics if we divide any number with 0 we will get infinity but in programming we will get an ERROR

In [18]:
10/0

ZeroDivisionError: division by zero

## But in numpy we will get the warning but there will not be any error

In [19]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
a/d

C:\Users\ACER\AppData\Local\Temp\ipykernel_16560\3201205449.py:1: RuntimeWarning: divide by zero encountered in divide
  a/d


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [24]:
d/d

C:\Users\ACER\AppData\Local\Temp\ipykernel_16560\2337618042.py:1: RuntimeWarning: invalid value encountered in divide
  d/d


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

## Universal Array Function

## To get the square Root

In [26]:
 arr = np.arange(0,11)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

## For Max or Min

In [31]:
np.max(arr)

10

In [32]:
np.min(arr)

0

## For LOG

In [33]:
np.log(arr)

C:\Users\ACER\AppData\Local\Temp\ipykernel_16560\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

## For Sin

In [34]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

## For COS

In [35]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

## For more ufunc check this official link
https://numpy.org/doc/stable/reference/ufuncs.html