## This notebook provides a collection of 10 beginner-level practice problems for learning NumPy, accompanied by solutions. Import the NumPy library before starting the exercises.

## # Importing NumPy

In [1]:
import numpy as np

## Problem 1: Create an Array of Zeros
### 
Create a NumPy array of size 10 filled with zeros.


In [2]:
# Solution to Problem 1
zero_array = np.zeros(10)
zero_array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Problem 2: Array of Tens
### 
Create a NumPy array of size 10 filled with the number ten.


In [3]:
# Solution to Problem 2
ten_array = np.full(10, 10)
ten_array


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

## Problem 3: Array of the First Ten Natural Numbers
### 
Create an array containing the first ten natural numbers.


In [4]:
# Solution to Problem 3
natural_numbers = np.arange(1, 11)
natural_numbers


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Problem 4: 2D Zero Array
### 
Create a 2x3 array filled with zeros.


In [5]:
# Solution to Problem 4
array_2d_zeros = np.zeros((2, 3))
array_2d_zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

## Problem 5: Identity Matrix
### 
Generate a 5x5 identity matrix.


In [6]:
# Solution to Problem 5
identity_matrix = np.eye(5)
identity_matrix


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Problem 6: Random Numbers Between 0 and 1
### 
Create an array of 10 random numbers between 0 and 1.


In [7]:
# Solution to Problem 6
random_numbers = np.random.rand(10)
random_numbers


array([0.98352152, 0.08000351, 0.24271592, 0.89514229, 0.75146809,
       0.98647114, 0.40815668, 0.90674668, 0.75992026, 0.61525747])

## Problem 7: Evenly Spaced Numbers
### 
Generate an array of 20 linearly spaced points between 0 and 5.


In [8]:
# Solution to Problem 7
linearly_spaced = np.linspace(0, 5, 20)
linearly_spaced


array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Problem 8: Set Random Seed
### 
Set the seed for NumPy's random number generator to 0 and generate five random numbers.


## If you set the np.random.seed(a_fixed_number) every time you call the numpy's other random function, the result will be the same:

In [14]:
# Solution to Problem 8
np.random.seed(0)
random_numbers_seed = np.random.rand(5)
random_numbers_seed


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

## Problem 9: 3x3 Array of Random Integers
### 
Create a 3x3 NumPy array of random integers in the range from 10 to 50.


In [12]:
# Solution to Problem 9
random_integers = np.random.randint(10, 50, size=(3, 3))
random_integers


array([[31, 46, 33],
       [16, 34, 34],
       [22, 11, 48]])

## Problem 10: Array Mean
### 
Find the mean of the array you created in Problem 9.


In [13]:
# Solution to Problem 10
mean_value = random_integers.mean()
mean_value


30.555555555555557