# 10 Intermediate Numpy Problems with Solutions
## 
This notebook contains a series of intermediate-level problems designed to increase your proficiency with NumPy, especially focusing on more complex array manipulations, statistics, linear algebra, and random data generation.

In [1]:
# Importing NumPy
import numpy as np


## Problem 1: Reshape Array
### Reshape an array of shape (10,) into shape (2, 5).


In [2]:
# Solution to Problem 1
arr = np.arange(10)
reshaped_arr = arr.reshape(2, 5)
reshaped_arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Problem 2: Vertical Stack
## 
Vertically stack the following two arrays: a = [1, 2, 3], b = [4, 5, 6].


In [3]:
# Solution to Problem 2
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked = np.vstack((a, b))
vstacked


array([[1, 2, 3],
       [4, 5, 6]])

## Problem 3: Horizontal Stack
### 
Horizontally stack two 2D arrays of shape (2, 3).


In [4]:
# Solution to Problem 3
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
hstacked = np.hstack((a, b))
hstacked


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Problem 4: Boolean Indexing
### 
Create an array of shape (10,) of random integers in the range [1, 100] and replace all values greater than 50 with the number 50.


In [5]:
# Solution to Problem 4
arr = np.random.randint(1, 100, size=10)
arr[arr > 50] = 50
arr


array([50, 50, 50,  8, 50, 50, 12, 11, 50, 50])

## Problem 5: Random Float Array Sum
### 
Create a 4x4 array of random floats and calculate the sum of all the elements.


In [6]:
# Solution to Problem 5
arr = np.random.rand(4, 4)
total_sum = arr.sum()
total_sum


8.947798977590566

## Problem 6: Array Element-wise Multiplication
Multiply two 3x3 matrices element-wise.


In [7]:
# Solution to Problem 6
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
element_wise_product = np.multiply(a, b)
element_wise_product


array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

## Problem 7: Matrix Multiplication
Perform a matrix multiplication between two 3x3 matrices.


In [8]:
# Solution to Problem 7
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_product = np.dot(a, b)
matrix_product


array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

## Problem 8: Extract Diagonal Elements
Extract the diagonal elements of a 4x4 matrix.


In [9]:
# Solution to Problem 8
matrix = np.arange(16).reshape(4, 4)
diagonal = np.diag(matrix)
diagonal


array([ 0,  5, 10, 15])

## Problem 9: Calculate Eigenvalues and Eigenvectors
Calculate the eigenvalues and eigenvectors of a 3x3 matrix.


In [10]:
# Solution to Problem 9
matrix = np.array([[4, 2, 1], [6, 5, 3], [9, 9, 9]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
eigenvalues, eigenvectors


(array([14.4650316 ,  2.88883605,  0.64613234]),
 array([[-0.1610977 , -0.36195045,  0.32296783],
        [-0.38954099, -0.24818321, -0.79687827],
        [-0.90681053,  0.89855271,  0.51056518]]))

## Problem 10: Sort an Array
Sort an array of random integers, size 10, in ascending order.


In [11]:
# Solution to Problem 10
arr = np.random.randint(1, 100, size=10)
sorted_arr = np.sort(arr)
sorted_arr


array([25, 40, 47, 48, 55, 63, 64, 80, 80, 84])