# 10 Advanced NumPy Problems with Solutions
### 
This notebook explores advanced NumPy functionalities including performance considerations, use of masked arrays, advanced indexing, polynomial fitting, Fourier transforms, and more.

In [1]:
# Importing NumPy
import numpy as np


## Problem 1: Broadcast Operations
Use broadcasting to add a 1D array of shape (3,) to a 2D array of shape (3,3) without using loops.


In [2]:
# Solution to Problem 1
a = np.array([1, 2, 3])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = a[:, np.newaxis] + b
result


array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

## Problem 2: Memory Layout
Create a 2D array (10000x10000) and copy it to another array with a Fortran-like memory layout. Measure and compare the time taken to sum along rows and columns for both arrays.


In [4]:
# Solution to Problem 2
import time

a = np.random.rand(10000, 10000)
b = np.copy(a, order='F')

start_c = time.time()
np.sum(a, axis=0)
end_c = time.time()

start_f = time.time()
np.sum(b, axis=0)
end_f = time.time()

time_c = end_c - start_c
time_f = end_f - start_f

time_c, time_f


(1.0667188167572021, 1.1097724437713623)

## Problem 3: Advanced Indexing
Extract elements from a 4x4 array that are greater than the mean value of the array.


In [5]:
# Solution to Problem 3
a = np.random.rand(4, 4)
mean_val = a.mean()
result = a[a > mean_val]
result


array([0.90636035, 0.5397746 , 0.86941117, 0.59543257, 0.62365536,
       0.86673634, 0.55510618, 0.71789628, 0.70724113, 0.51608334])

## Problem 4: Strided Manipulation
Create a sliding window sum of a 1D array of length 10 with a window size of 3.


In [6]:
# Solution to Problem 4
def sliding_window_sum(arr, window_size):
    return np.convolve(arr, np.ones(window_size), 'valid')

arr = np.arange(10)
sliding_window_sum(arr, 3)


array([ 3.,  6.,  9., 12., 15., 18., 21., 24.])

## Problem 5: Compute the Determinant
Compute the determinant of a randomly generated 10x10 matrix.
et


In [7]:
# Solution to Problem 5
a = np.random.rand(10, 10)
det = np.linalg.det(a)
det


-0.002409016453886752

## Problem 6: Solve Simultaneous Linear Equations
Solve the linear equations 3x + 4y = 5 and 2x - y = 1 using NumPy.


In [8]:
# Solution to Problem 6
A = np.array([[3, 4], [2, -1]])
b = np.array([5, 1])
x, y = np.linalg.solve(A, b)
x, y


(0.8181818181818182, 0.6363636363636364)

## Problem 7: Eigenvalues and Eigenvectors
Find the eigenvalues and eigenvectors of a 5x5 matrix.


In [9]:
# Solution to Problem 7
matrix = np.random.rand(5, 5)
eigenvalues, eigenvectors = np.linalg.eig(matrix)
eigenvalues, eigenvectors


(array([ 2.36642369+0.j        ,  0.83195074+0.j        ,
        -0.25823106+0.28457163j, -0.25823106-0.28457163j,
        -0.17929277+0.j        ]),
 array([[-0.49152654+0.j        ,  0.39368389+0.j        ,
         -0.5843152 +0.j        , -0.5843152 -0.j        ,
          0.14355222+0.j        ],
        [-0.25423432+0.j        , -0.57950714+0.j        ,
         -0.17036961+0.12667224j, -0.17036961-0.12667224j,
         -0.44258779+0.j        ],
        [-0.51698253+0.j        , -0.25501211+0.j        ,
          0.09512842+0.11174508j,  0.09512842-0.11174508j,
          0.35735214+0.j        ],
        [-0.38172653+0.j        , -0.3431884 +0.j        ,
          0.12951023-0.56612162j,  0.12951023+0.56612162j,
          0.70328722+0.j        ],
        [-0.52988724+0.j        ,  0.57129241+0.j        ,
          0.49259637+0.10977219j,  0.49259637-0.10977219j,
         -0.40149141+0.j        ]]))

## Problem 8: Fast Fourier Transform
Apply the Fast Fourier Transform to a sinewave signal generated with NumPy.


In [10]:
# Solution to Problem 8
t = np.linspace(0, 1, 500, endpoint=False)
signal = np.sin(2 * np.pi * 5 * t)
fft_result = np.fft.fft(signal)
fft_result


array([-2.33823717e-14+0.00000000e+00j,  6.99270432e-15+6.88338275e-15j,
       -4.48409087e-14+3.76895980e-14j, -5.05168484e-14-4.09672296e-14j,
        1.79767651e-14-1.46573803e-14j, -7.36026246e-14-2.50000000e+02j,
        2.57054586e-15-4.16826374e-14j,  5.66495145e-15-1.68134704e-14j,
       -1.15495627e-14-2.17038586e-14j, -9.81745563e-15-1.83942687e-15j,
        7.30319124e-15-3.34527370e-14j,  2.79868034e-14-3.05944005e-14j,
       -2.26049387e-14+6.06547971e-14j, -3.18130422e-14-6.62845702e-14j,
        3.07402130e-14-3.25905503e-14j, -1.18259103e-14-1.42108547e-14j,
        2.03043969e-14-1.22233140e-14j,  4.23466739e-15-5.74634411e-15j,
        1.36583095e-14-6.76376345e-15j, -1.88237320e-14+1.84976405e-14j,
        1.53288592e-14-3.73307790e-14j,  2.02447327e-14-2.38181468e-14j,
        3.56828481e-15+2.50384215e-14j,  1.30497404e-14-1.47214647e-14j,
        7.44224315e-15+1.33453478e-14j,  4.92345587e-15-5.25161357e-15j,
       -7.60480810e-15+1.76489424e-14j,  9.03309450

## Problem 9: Masked Array
Create a masked array to ignore outlier values greater than 90 in a dataset.


In [11]:
# Solution to Problem 9
data = np.random.randint(0, 100, size=50)
masked_data = np.ma.masked_where(data > 90, data)
masked_data


masked_array(data=[55, 18, 15, 30, 15, 26, 20, --, 85, 69, 83, 33, 72, 47,
                   83, 30, 83, 0, 47, 5, 43, --, 61, 36, 30, --, 16, 7,
                   27, 7, 49, 8, 67, 1, 78, 63, 88, 84, 74, 41, 55, 70,
                   33, 25, 66, --, --, 21, 29, 25],
             mask=[False, False, False, False, False, False, False,  True,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False,  True, False, False,
                   False,  True, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False,  True,  True, False,
                   False, False],
       fill_value=999999)

## Problem 10: Polynomial Fitting
Fit a polynomial of degree 3 to the points (1,2), (3,4), and (5,6) and evaluate the polynomial at x=4.


In [12]:
# Solution to Problem 10
x_points = np.array([1, 3, 5])
y_points = np.array([2, 4, 6])
coeffs = np.polyfit(x_points, y_points, 3)
poly = np.poly1d(coeffs)
evaluated_at_4 = poly(4)
evaluated_at_4


C:\Users\ACER\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3526: RankWarning: Polyfit may be poorly conditioned
  exec(code_obj, self.user_global_ns, self.user_ns)


5.0245657889066075